# Generated by Django 6.1.1 on 2026-09-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expenses", "0001_initial"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="expenses", to="tags.tag"
            ),
        ),
    ]
