# Generated by Django 6.1.1 on 2026-09-24 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0002_initial"),
        ("currencies", "0001_initial"),
        ("expenses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="recurringexpense",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recurring_expenses",
                to="categories.category",
            ),
        ),
        migrations.AddField(
            model_name="recurringexpense",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recurring_expenses",
                to="currencies.currency",
            ),
        ),
        migrations.AddField(
            model_name="recurringexpense",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="recurring_expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="expenses.recurringexpense",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringexpense",
            index=models.Index(
                fields=["user", "next_date", "is_active"],
                name="recurring_e_user_id_dee95f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["user", "date"], name="expenses_user_id_513cb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["user", "category"], name="expenses_user_id_ea8763_idx"
            ),
        ),
    ]
