# Generated by Django 6.1.1 on 2026-09-24 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budgets", "0001_initial"),
        ("categories", "0001_initial"),
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty for total budget",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="categories.category",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="currencies.currency",
            ),
        ),
    ]
